import random
# GAME GENERATED BY RITURAJ USING PYTHON
# HOPE YOU WILL ENJOY THE GAME
random = random.randint(0,100)
x = attempt = 1
print("Game developed by Rituraj")
print("================================================")
while(x==1):
    user = int(input("Guess the number: "))
    if user == random:
        print("Guessed the correct one")
        print("Bot generated :"+str(random)+" You guessed :"+str(random))
        print("Attempt you took: "+str(attempt))
        x=0
    elif user>random:
        print("Guess lower number")
        attempt += 1
        print("================================================")
    elif user<random:
        print("Guess upper number")
        attempt += 1
        print("================================================")
    
